### ISSUE TITLE
Post info dialog needs to be more human-friendly

### ISSUE THREAD

**Issue by perlatus** [perlatus/e1547#24]
Need to implement a friendlier post info dialog (in addition to the raw JSON). Especially important because post metadata is not available in the post widget itself yet.

**Comment by Youboontoo** [comment]
Just for reference:
![screen](https://user-images.githubusercontent.com/16302135/28494615-550d5620-6ee8-11e7-8a42-e964b32e328f.png)

**Comment by perlatus** [comment]
Need to also consider fake "artist" tags, like "conditional_dnp" and "sound_warning".
