### ISSUE TITLE
Can't exit fullscreen view on iOS

### ISSUE THREAD

**Issue by ArthurRasmusson** [perlatus/e1547#32]
Once image is clicked the app must be killed from the iOS task switcher and relaunched before it returns to the menu view.

A gesture to exit fullscreen would improve usability a great deal.

**Comment by perlatus** [comment]
Good to know that it mostly works on iOS.

I'm planning to eventually combine the fullscreen/pinch-to-zoom view with the normal post view; for now, how does single-tap to go back sound?

**Comment by ArthurRasmusson** [comment]
Ya, so far the app works wonderfully on iOS! 

The one exception I have found is text boxes not functioning with iOS's native typing cursor movement. Generally you can force touch and swipe the keyboard to move your cursor backward or forward through a text box to edit text. I would imagine this bug has more to do with Flutter's cross-platform support than it does with your implementation. 

I'm just happy to have a native app for this site on iOS finally. Thanks for making this!

Single tap to go back would be a great improvement. :)

**Comment by ArthurRasmusson** [comment]
Another note:

I suspect the prudes who handle approving apps for Apple's App Store will reject any "booru-like" app. A Booru app called "Andbooru" was rejected when attempting to list in the App Store in 2014 and sadly the developer did not post he .ipa anywhere for iOS user's to self sign install from iTunes.

With this possibility in mind once the app reaches a level of maturity you deem up to your standards for release in the Google Play Store / fdroid for Android I suggest posting your iOS builds in .deb format to BigBoss's Cydia repository for those of us who have jailbroken our iOS devices, and for those who have not jailbroken posting a download link to the .ipa file in the GitHub readme.md would be sufficient for iOS users who have similarly taken an interest in this app to self sign the .ipa and install it to their iOS device from iTunes bypassing Apple's strict App Store.

**Comment by ArthurRasmusson** [comment]
Also if you do not have a Mac for xcode you can setup a MacOS virtual machine to produce builds for iOS.

If you would rather not go through the trouble then with your permission I would be willing to produce some builds for iOS and list them on Big Boss's Cydia repository. Many members of the iOS jailbreak community would appreciate convenient access this way.

**Comment by perlatus** [comment]
I'm not currently interested in packaging for Cydia, so feel free to go ahead if you want. (I also can't technically stop you because of the license; just don't do anything evil, etc.)

I do now have a used MBP, but I'm going to focus on making the app suitable for official release.

**Comment by perlatus** [comment]
Fixed by bb15753dce24080ee731f8db9669cd432b4b6bde
