### ISSUE TITLE
CloudFlare DDOS protection on API endpoint breaks app

### ISSUE THREAD

**Issue by ghost** [perlatus/e1547#33]
I believe the fact that this "FormatException" error is thrown only while on VPN has something to do with the website's use of CloudFlare ddos protection and how they handle verifying the web request was not sent by a robot which is to totally replace the website front page asking you to authenticate using Google's Captcha so that you can get the cookie in order to proceed past the CloudFlare ddos protection page. 

Perhaps some sort of frame to pass through the captcha from the page into the app in the event of the CloudFlare block in order to obtain the cookie CloudFlare demands before it lets you through to the site.

![Error screenshot](http://i.imgur.com/DQydN3f.png)

**Comment by perlatus** [comment]
This is something I'll probably have to ask on e926 since I don't see a workaround. There's no way to do in-app web-browsing in the engine I'm using for the app. I'm consuming the JSON API, so getting back HTML at all is strange.

**Comment by perlatus** [comment]
In a way, the request was sent by a robot. Hah... But all requests sent to the API should be expected to come from a bot.

**Comment by perlatus** [comment]
Whaddayaknow, looks like we can launch a WebViewActivity and grab the cookies: https://github.com/dart-flitter/flutter_webview_plugin/commit/0f97a37935c7ab58ff490fc781a656506cac0c39
