### ISSUE TITLE
No flash on iOS

### ISSUE THREAD

**Issue by ArthurRasmusson** [perlatus/e1547#35]
iOS has no means of running flash content yet searches return Flash content effectively adding noise to the search. Can we get a way to filter this so it does not show up in the search results? A flag under settings to do this globally would be even better.

**Comment by perlatus** [comment]
I think this could be satisfied by #30

**Comment by perlatus** [comment]
Turned out to be more complicated than originally thought to get the local blacklist working, so I'm just going to add an option in the settings for now.

https://github.com/perlatus/e1547/tree/hideswf (not currently working)

**Comment by perlatus** [comment]
Resolved by 6cc01fa78c8961a6cdd10e7875d695f44179509e
