### ISSUE TITLE
Download, share, and export posts

### ISSUE THREAD

**Issue by perlatus** [perlatus/e1547#4]
Post contents include images, videos, and flash files.

- [x] Download and share post contents.
- [ ] Bulk download post contents.
- [ ] Export to cloud storage providers as well as local storage
- [x] Copy and paste links to posts and searches

So this requires some additional UI for selecting multiple posts (e.g from a gallery view). Some sort of download manager so that we don't open up too many requests at once.

It would also be nice for the filename and folder hierarchy to be configurable, given access to post metadata.

**Comment by perlatus** [comment]
Sharing binary data [isn't supported by the share flutter plugin](https://github.com/flutter/plugins/blob/dc930976d354d8f76bd4972959ca7f48fa4b95a6/packages/share/android/src/main/java/io/flutter/plugins/share/SharePlugin.java#L48).

We need some [extra stuff](https://developer.android.com/training/sharing/send.html#send-binary-content) to be share binary data.

This shouldn't impact downloading.

**Comment by perlatus** [comment]
Dammit, [downloading isn't supported either.](https://github.com/flutter/plugins/blob/master/packages/path_provider/lib/path_provider.dart) Going to need another plugin for writing to SD card (and how would that work on iOS?).

**Comment by perlatus** [comment]
Need to create an Android-only plugin for writing files to sdcard. The [`StandardMessageCodec`](https://docs.flutter.io/flutter/services/StandardMessageCodec-class.html) supports `List<Uint8>` (java: `byte[]`) which means we can send the path+filename and binary data over a `MethodChannel`. This would allow doing the downloading in dart+flutter rather than using something like Android's DownloadManager.

This is going to require handling the image bytes ourselves and passing them around (e.g. as a  [`MemoryImage`](https://docs.flutter.io/flutter/services/MemoryImage-class.html) rather than a [`NetworkImage`](https://docs.flutter.io/flutter/services/NetworkImage-class.html)), so need to keep in mind [plans for the offline post and image cache](https://github.com/perlatus/e1547/issues/9).

**Comment by perlatus** [comment]
Simpler solution: import `dart:io`, add [`WRITE_EXTERNAL_STORAGE`](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE), and use [`path_provider#getExternalStorageDirectory`](https://github.com/flutter/plugins/blob/ff276b8db9906574634b9f257b02bf0d94d50970/packages/path_provider/lib/path_provider.dart#L55).

**Comment by Skylled** [comment]
In most cases, I would think sharing the image link would suffice, which is supported by the Share plugin. I was trying the app out (love it!) and wanted to share a photo, instead had to pop to Firefox and share from there which also only shared the image link.

**Comment by perlatus** [comment]
I haven't found sharing the link to be any better than copy-paste. For example: sharing the binary image itself to bluetooth sends the image rather than just the link, sharing the binary image to dropbox would save the image itself rather than a text file containing a link to the image. Sharing the image link to dropbox would probably just save a text file with the link in it, which doesn't make sense to me as a user.

Tried it out In firefox, and I'm pretty sure the long-tap/share shares the binary image since I can send it over bluetooth (... although haven't confirmed by checking the source)

That said, if you have some examples where sharing the URL comes in handy, I'll happily accept whatever you send over.
